### PR TITLE
Change to MIT license

### PR DESCRIPTION
**Pull request by naveen521kk**
All the authors and contributors have agreed to this change.

Fixes https://github.com/ManimCommunity/manim/issues/2418

### CODE REVIEW

**Comment by naveen521kk** [comment]
Pinging all contributors so they are aware of this change: @PhilippImhof, @RickyC0626, @marcin-serwin, @jsonvillanueva

**Review by PhilippImhof — APPROVED** [review]

**Comment by naveen521kk** [comment]
It looks like it's fine to license ManimPango under MIT license, as an example I saw the gtk-rs project today, its license: https://github.com/gtk-rs/gtk-rs-core/blob/166f0055bffbfc8c05b4f621d4d7704a00a21c24/COPYRIGHT

While the code here for binding will be licensed under MIT license the wheels that are distributed on PyPI is subject to GNU LGPL, the license is [here](https://github.com/ManimCommunity/ManimPango/blob/6b5837dbdea674dfd81347f3f6b42060d86a9633/packing/LICENSE.bin). I think I should add a note about that on README and also change the license in `setup.py`.

**Review by PhilippImhof — APPROVED** [review]
LGTM

**Comment by naveen521kk** [comment]
We should make a new release now, right? What should be its version, I guess bump minor version?

**Comment by PhilippImhof** [comment]
Absolutely. I'd say this should be a post release according to PEP 440:

> Some projects use post-releases to address minor errors in a final release that do not affect the distributed software (for example, correcting an error in the release notes).

**Comment by naveen521kk** [comment]
I'll do later this evening. Thanks

**Pull request merged**
