### PR TITLE
Stable API

### PR DESCRIPTION
**Pull request by naveen521kk**
I would working over this month on this. For now this is just a draft on how this will look.

Fixes https://github.com/ManimCommunity/ManimPango/issues/28
Also, Fixes https://github.com/ManimCommunity/ManimPango/issues/37 and Fixes https://github.com/ManimCommunity/ManimPango/issues/30

### CODE REVIEW

**Comment by naveen521kk** [comment]
For now, an example of using the API would be
```py
>>> from manimpango import *
>>> l = Layout(markup="<span color='BLUE' font_family='Cursive'>Blue</span>")
>>> r = SVGRenderer('blue.svg', 100, 100, l, move_to=(25,25))
>>> r.render()
True
```
and an SVG file like this would be created.
[blue.zip](https://github.com/ManimCommunity/ManimPango/files/6565215/blue.zip)

@PhilippImhof does this look good? Any suggestions?

**Comment by naveen521kk** [comment]
After implementing Image backend this is done :).

**Comment by PhilippImhof** [comment]
This looks very nice at the first glance. As it is a very substantial change (and step forward), I would like to take some time to really look at it in details.

**Comment by naveen521kk** [comment]
Sure, you could look into this now or later when I complete the image backend. There are many codes that aren't used currently only the image backend will use it.

**Comment by naveen521kk** [comment]
I think I would something from scratch rather than working on this. So closing.

**Pull request closed without merging**
