### PR TITLE
Windows: Loading font from file

### PR DESCRIPTION
**Pull request by naveen521kk**
### Changes
- This uses Windows Specific API to add font file to search path
  doing so makes Pango find the font even if it is not installed
  and this is same as adding to fontconfig's search path, as done in Linux.
  Works locally.
- Fixed a compiler warning caused by invalid data type from #9 

Possibly @PhilippImhof may know how to do so in macOS.

### CODE REVIEW

**Comment by naveen521kk** [comment]
@PhilippImhof Can we add any font to test? If yes, what to. We need to think about license also...

**Comment by naveen521kk** [comment]
I will merge this tomorrow if it doesn't get any review.

**Comment by PhilippImhof** [comment]
I cannot check the windows part, but will definitely have a look for Mac OS. Maybe you can request another reviewer before just merging it?

**Comment by naveen521kk** [comment]
> I cannot check the windows part
There are some tests checking things there (checks whether there are any warnings from Pango). So, I can be sure of saying that things work.
> but will definitely have a look for Mac OS
:+1: 
> Maybe you can request another reviewer before just merging it?
Don't know who to actually ask. Any suggestions?

**Comment by naveen521kk** [comment]
Also, can you look into the other parts of code I have edited?

**Review by leotrs — APPROVED** [review]

**Comment by naveen521kk** [comment]
I don't know how automerge worked now..

**Pull request merged**
