### PR TITLE
Add option to Register Fonts using Fc backend on Windows and macOS

### LINKED ISSUE #55: Add option to Register Fonts using Fc backend on Windows and macOS
Currently, if we changed PangoCairo backends, `register_font` won't work as expected. And shifting backend is as simple as `PANGOCARIO_BACKEND` variable to `fc`, this should work on both Wheels distributed on Windows and macOS. (This isn't a thing on Linux as Fontconfig is the default backend). This can help in testing because rendering would be the same if the font backends are the same.

### PR DESCRIPTION
**Pull request by naveen521kk**
Also, add some tests to test those
Fixes #55

### CODE REVIEW

**Comment by naveen521kk** [comment]
Pytest fixtures and parametrize are super cool!

**Comment by naveen521kk** [comment]
@PhilippImhof can you give this a review?

**Comment by naveen521kk** [comment]
ping @PhilippImhof

**Review by PhilippImhof — APPROVED** [review]
SGTM

**Pull request merged**
