### PR TITLE
Add support for PangoAttributes

### PR DESCRIPTION
**Pull request by naveen521kk**
This is still a WIP and would introduce a new API which would be required for https://github.com/ManimCommunity/manim/issues/2355

### CODE REVIEW

**Comment by PhilippImhof** [comment]
I will have a look at this during the weekend.

**Comment by naveen521kk** [comment]
This PR introduces a new class called `TextAttribute`. This can't be used with the current API and would require an entirely new API for this to work. `TextAttribute` isn't fully done and misses a lot of attributes; that's for another day.

I think it would be better to just merge this because no one would be able to review this since this would be an entire rewrite of this project.

**Comment by PhilippImhof** [comment]
OK, that's fine for me. Go for it.

**Comment by PhilippImhof** [comment]
Oh, and thanks :)

**Pull request merged**
