### PR TITLE
macOS: build a shared library in wheels

### PR DESCRIPTION
**Pull request by naveen521kk**

### CODE REVIEW

**Comment by PhilippImhof** [comment]
What are we doing about the failing tests?

**Comment by naveen521kk** [comment]
> What are we doing about the failing tests?

I know why the tests were failing https://www.msys2.org/news/#2021-12-21-potential-incompatibilities-with-newer-python-setuptools, I will fix them soon.

**Comment by naveen521kk** [comment]
Also, it would be better if you test whether the tests work with the in the PR: https://github.com/ManimCommunity/manim/pull/2341

**Comment by PhilippImhof** [comment]
I will do so, probably tomorrow (UTC+1)

**Comment by naveen521kk** [comment]
> What are we doing about the failing tests?

Normal windows test also fails, I just thought msys2 one failed. I will see what is really happening.

**Review by PhilippImhof — APPROVED** [review]
LGTM. Tested pre-built wheels locally.

**Comment by PhilippImhof** [comment]
Tested with code from ManimCommunity/manim#2341. Using these wheels, tests work. Using statically linked wheels from main branch, tests crash locally just like they do in CI.

**Pull request merged**
